### ISSUE TITLE
error message show 

### ISSUE THREAD

**Issue by sgnxsjh** [sgnxsjh/oneday#1]
F:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.4\helpers\pycharm\utrunner.py" F:\SJHCode\SJH-2017code\20171023\SCREEN\test_chrome.py true
Testing started at 13:58 ...

Error
Traceback (most recent call last):
  File "F:\SJHCode\SJH-2017code\20171023\SCREEN\test_chrome.py", line 32, in test_open_and_search
    driver.find_element_by_id("kw").clear()
  File "F:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 88, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "F:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 457, in _execute
    return self._parent.execute(command, params)
  File "F:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "F:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.16299 x86_64)

Process finished with exit code 0

**Comment by sgnxsjh** [comment]
closed ，resolved.  version update.driver should update too

**Comment by sgnxsjh** [comment]
version update.driver should update too
